// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
	"strconv"
)

type GSXShellSlots struct {
	Default func(gsxio.Writer) error
}

func RenderShell(w gsxio.Writer, title string) error {
	return renderShell(w, GSXShellSlots{}, title)
}

func RenderShellWithSlots(w gsxio.Writer, slots GSXShellSlots, title string) error {
	return renderShell(w, slots, title)
}

func renderShell(w gsxio.Writer, __gsx_slots GSXShellSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title><script src=\"https://unpkg.com/htmx.org@1.9.12\"></script></head><body>"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXUserRowSlots struct{}

func RenderUserRow(w gsxio.Writer, user User) error {
	return renderUserRow(w, GSXUserRowSlots{}, user)
}

func RenderUserRowWithSlots(w gsxio.Writer, slots GSXUserRowSlots, user User) error {
	return renderUserRow(w, slots, user)
}

func renderUserRow(w gsxio.Writer, __gsx_slots GSXUserRowSlots, user User) error {
	if err := gsxrt.WriteString(w, "<tr"); err != nil {
		return err
	}
	if err := gsxrt.WriteAttrString(w, "id", string("user-"+strconv.Itoa(user.ID))); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "><td>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
		return err
	}
	return nil
}

type GSXUsersTableSlots struct{}

func RenderUsersTable(w gsxio.Writer, users []User) error {
	return renderUsersTable(w, GSXUsersTableSlots{}, users)
}

func RenderUsersTableWithSlots(w gsxio.Writer, slots GSXUsersTableSlots, users []User) error {
	return renderUsersTable(w, slots, users)
}

func renderUsersTable(w gsxio.Writer, __gsx_slots GSXUsersTableSlots, users []User) error {
	if err := gsxrt.WriteString(w, "<table class=\"users-table\"><thead><tr><th>Name</th><th>Email</th></tr></thead><tbody>"); err != nil {
		return err
	}
	for _, user := range users {
		{
			user := user
			if err := gsxrt.WriteString(w, "<tr"); err != nil {
				return err
			}
			if err := gsxrt.WriteAttrString(w, "id", string("user-"+strconv.Itoa(user.ID))); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "><td>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
				return err
			}
		}
	}
	if err := gsxrt.WriteString(w, "</tbody></table>"); err != nil {
		return err
	}
	return nil
}

type GSXUsersPageSlots struct{}

func RenderUsersPage(w gsxio.Writer, users []User) error {
	return renderUsersPage(w, GSXUsersPageSlots{}, users)
}

func RenderUsersPageWithSlots(w gsxio.Writer, slots GSXUsersPageSlots, users []User) error {
	return renderUsersPage(w, slots, users)
}

func renderUsersPage(w gsxio.Writer, __gsx_slots GSXUsersPageSlots, users []User) error {
	{
		title := "HTMX Users"
		if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>"); err != nil {
			return err
		}
		if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
			return err
		}
		if err := gsxrt.WriteString(w, "</title><script src=\"https://unpkg.com/htmx.org@1.9.12\"></script></head><body><main><h1>Users</h1><div hx-get=\"/users\" hx-trigger=\"load\" hx-swap=\"innerHTML\">"); err != nil {
			return err
		}
		{
			users := users
			if err := gsxrt.WriteString(w, "<table class=\"users-table\"><thead><tr><th>Name</th><th>Email</th></tr></thead><tbody>"); err != nil {
				return err
			}
			for _, user := range users {
				{
					user := user
					if err := gsxrt.WriteString(w, "<tr"); err != nil {
						return err
					}
					if err := gsxrt.WriteAttrString(w, "id", string("user-"+strconv.Itoa(user.ID))); err != nil {
						return err
					}
					if err := gsxrt.WriteString(w, "><td>"); err != nil {
						return err
					}
					if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
						return err
					}
					if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
						return err
					}
					if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
						return err
					}
					if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
						return err
					}
				}
			}
			if err := gsxrt.WriteString(w, "</tbody></table>"); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</div></main></body></html>"); err != nil {
			return err
		}
	}
	return nil
}
