// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXBaseLayoutSlots struct {
	Head    func(gsxio.Writer) error
	Header  func(gsxio.Writer) error
	Default func(gsxio.Writer) error
	Footer  func(gsxio.Writer) error
}

func RenderBaseLayout(w gsxio.Writer, title string) error {
	return renderBaseLayout(w, GSXBaseLayoutSlots{}, title)
}

func RenderBaseLayoutWithSlots(w gsxio.Writer, slots GSXBaseLayoutSlots, title string) error {
	return renderBaseLayout(w, slots, title)
}

func renderBaseLayout(w gsxio.Writer, __gsx_slots GSXBaseLayoutSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title>"); err != nil {
		return err
	}
	if __gsx_slots.Head != nil {
		if err := __gsx_slots.Head(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</head><body><header>"); err != nil {
		return err
	}
	if __gsx_slots.Header != nil {
		if err := __gsx_slots.Header(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</header><main>"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</main><footer>"); err != nil {
		return err
	}
	if __gsx_slots.Footer != nil {
		if err := __gsx_slots.Footer(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</footer></body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXAuthLayoutSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
	Footer  func(gsxio.Writer) error
}

func RenderAuthLayout(w gsxio.Writer, title string) error {
	return renderAuthLayout(w, GSXAuthLayoutSlots{}, title)
}

func RenderAuthLayoutWithSlots(w gsxio.Writer, slots GSXAuthLayoutSlots, title string) error {
	return renderAuthLayout(w, slots, title)
}

func renderAuthLayout(w gsxio.Writer, __gsx_slots GSXAuthLayoutSlots, title string) error {
	{
		title := title
		if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
			return err
		}
		if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
			return err
		}
		if err := gsxrt.WriteString(w, "</title>"); err != nil {
			return err
		}
		if __gsx_slots.Head != nil {
			if err := __gsx_slots.Head(w); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</head><body><header><div class=\"topbar\"><strong>Secure Area</strong></div></header><main><section class=\"auth-shell\">"); err != nil {
			return err
		}
		if __gsx_slots.Default != nil {
			if err := __gsx_slots.Default(w); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</section></main><footer>"); err != nil {
			return err
		}
		if __gsx_slots.Footer != nil {
			if err := __gsx_slots.Footer(w); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</footer></body></html>"); err != nil {
			return err
		}
	}
	return nil
}

type GSXProfilePageSlots struct{}

func RenderProfilePage(w gsxio.Writer, data ProfileData) error {
	return renderProfilePage(w, GSXProfilePageSlots{}, data)
}

func RenderProfilePageWithSlots(w gsxio.Writer, slots GSXProfilePageSlots, data ProfileData) error {
	return renderProfilePage(w, slots, data)
}

func renderProfilePage(w gsxio.Writer, __gsx_slots GSXProfilePageSlots, data ProfileData) error {
	{
		title := data.Title
		{
			title := title
			if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</title><meta name=\"description\""); err != nil {
				return err
			}
			if err := gsxrt.WriteAttrString(w, "content", string(data.Description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, " /></head><body><header><div class=\"topbar\"><strong>Secure Area</strong></div></header><main><section class=\"auth-shell\"><section><h1>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(data.Title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</h1><p>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(data.Description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</p><dl><dt>Email</dt><dd>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(data.Email)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</dd><dt>Role</dt><dd>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(data.Role)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</dd></dl></section></section></main><footer><div><small>Signed in as "); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(data.Email)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</small></div></footer></body></html>"); err != nil {
				return err
			}
		}
	}
	return nil
}
