package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	stdhtml "html"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/jlcsoftgenie/gsx/internal/ast"
	"github.com/jlcsoftgenie/gsx/internal/compiler"
	"github.com/jlcsoftgenie/gsx/internal/diagnostics"
)

type importSpec struct {
	Alias string
	Path  string
}

type generator struct {
	pkg     *compiler.Package
	file    *ast.File
	buf     bytes.Buffer
	indent  int
	ioAlias string
	rtAlias string
	curComp *compiler.Component
	static  strings.Builder
}

func GenerateFile(pkg *compiler.Package, file *ast.File) ([]byte, error) {
	g := &generator{pkg: pkg, file: file, ioAlias: "gsxio", rtAlias: "gsxrt"}
	if err := g.generate(); err != nil {
		return nil, err
	}
	formatted, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), err
	}
	return formatted, nil
}

func (g *generator) generate() error {
	g.line("// Code generated by gsx. DO NOT EDIT.")
	g.line("")
	g.line("package %s", g.file.Package)
	g.line("")
	imports, err := g.collectImports()
	if err != nil {
		return err
	}
	g.line("import (")
	g.indent++
	for _, imp := range imports {
		switch imp.Alias {
		case "", path.Base(imp.Path):
			g.line("%q", imp.Path)
		default:
			g.line("%s %q", imp.Alias, imp.Path)
		}
	}
	g.indent--
	g.line(")")
	g.line("")
	for i, decl := range g.file.Components {
		comp := g.pkg.Components[decl.Name]
		g.curComp = comp
		g.emitSlotStruct(comp)
		g.line("func Render%s(w %s.Writer%s) error {", decl.Name, g.ioAlias, g.paramSignature(comp.Params))
		g.indent++
		g.line("return render%s(w, %s{}, %s)", decl.Name, slotTypeName(decl.Name), g.paramNames(comp.Params))
		g.indent--
		g.line("}")
		g.line("")
		g.line("func Render%sWithSlots(w %s.Writer, slots %s%s) error {", decl.Name, g.ioAlias, slotTypeName(decl.Name), g.paramSignature(comp.Params))
		g.indent++
		g.line("return render%s(w, slots, %s)", decl.Name, g.paramNames(comp.Params))
		g.indent--
		g.line("}")
		g.line("")
		g.line("func render%s(w %s.Writer, __gsx_slots %s%s) error {", decl.Name, g.ioAlias, slotTypeName(decl.Name), g.paramSignature(comp.Params))
		g.indent++
		if err := g.emitNodes(comp.Decl.Body, false, true); err != nil {
			return err
		}
		g.line("return nil")
		g.indent--
		g.line("}")
		if i < len(g.file.Components)-1 {
			g.line("")
		}
	}
	return nil
}

func (g *generator) collectImports() ([]importSpec, error) {
	byPath := map[string]importSpec{}
	for _, imp := range g.file.Imports {
		alias := imp.Alias
		if alias == "" {
			alias = path.Base(imp.Path)
		}
		byPath[imp.Path] = importSpec{Alias: alias, Path: imp.Path}
	}
	g.ioAlias = ensureImport(byPath, "io", g.ioAlias)
	g.rtAlias = ensureImport(byPath, "github.com/jlcsoftgenie/gsx/runtime", g.rtAlias)
	out := make([]importSpec, 0, len(byPath))
	for _, imp := range byPath {
		out = append(out, imp)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func (g *generator) emitSlotStruct(comp *compiler.Component) {
	name := slotTypeName(comp.Decl.Name)
	if len(comp.Slots) == 0 {
		g.line("type %s struct{}", name)
		g.line("")
		return
	}
	g.line("type %s struct {", name)
	g.indent++
	for _, slot := range comp.Slots {
		g.line("%s func(%s.Writer) error", slotField(slot), g.ioAlias)
	}
	g.indent--
	g.line("}")
	g.line("")
}

func (g *generator) emitNodes(nodes []ast.Node, stripSlot bool, flushFinal bool) error {
	for _, node := range nodes {
		if err := g.emitNode(node, stripSlot); err != nil {
			return err
		}
	}
	if flushFinal {
		g.flushStatic()
	}
	return nil
}

func (g *generator) emitNode(node ast.Node, stripSlot bool) error {
	switch n := node.(type) {
	case *ast.Text:
		g.appendStatic(n.Value)
	case *ast.Expr:
		g.flushStatic()
		g.emitExprWrite(n.Code, n.Span)
	case *ast.Comment:
		g.appendStatic("<!--" + n.Value + "-->")
	case *ast.Doctype:
		g.appendStatic("<!" + n.Value + ">")
	case *ast.If:
		g.flushStatic()
		if len(n.Branches) == 0 {
			return nil
		}
		g.line("if %s {", n.Branches[0].Cond)
		g.indent++
		if err := g.emitNodes(n.Branches[0].Body, false, true); err != nil {
			return err
		}
		g.indent--
		for _, branch := range n.Branches[1:] {
			g.line("} else if %s {", branch.Cond)
			g.indent++
			if err := g.emitNodes(branch.Body, false, true); err != nil {
				return err
			}
			g.indent--
		}
		if len(n.ElseBody) > 0 {
			g.line("} else {")
			g.indent++
			if err := g.emitNodes(n.ElseBody, false, true); err != nil {
				return err
			}
			g.indent--
		}
		g.line("}")
	case *ast.For:
		g.flushStatic()
		g.line("for %s {", n.Header)
		g.indent++
		if err := g.emitNodes(n.Body, false, true); err != nil {
			return err
		}
		g.indent--
		g.line("}")
	case *ast.Element:
		return g.emitElement(n, stripSlot)
	}
	return nil
}

func (g *generator) emitElement(elem *ast.Element, stripSlot bool) error {
	if elem.Name == "fragment" {
		return g.emitNodes(elem.Children, stripSlot, false)
	}
	if elem.Name == "slot" {
		g.flushStatic()
		name := "default"
		if attr, ok := elem.Attr("name"); ok && attr.Kind == ast.AttrString && attr.Value != "" {
			name = attr.Value
		}
		field := slotField(name)
		g.line("if __gsx_slots.%s != nil {", field)
		g.indent++
		g.line("if err := __gsx_slots.%s(w); err != nil {", field)
		g.indent++
		g.line("return err")
		g.indent--
		g.line("}")
		g.indent--
		g.line("}")
		return nil
	}
	if elem.Name == "raw" {
		g.flushStatic()
		attr, _ := elem.Attr("html")
		g.line("if err := %s.WriteRaw(w, %s); err != nil {", g.rtAlias, attr.Expr)
		g.indent++
		g.line("return err")
		g.indent--
		g.line("}")
		return nil
	}
	if elem.IsComponent() {
		if resolved, ok := g.pkg.ResolveComponent(g.file, elem.Name); ok {
			return g.emitComponentCall(resolved, elem)
		}
	}
	g.appendStatic("<" + elem.Name)
	for _, attr := range elem.Attributes {
		if stripSlot && attr.MetaSlot {
			continue
		}
		if attr.MetaSlot && elem.IsComponent() {
			continue
		}
		switch attr.Kind {
		case ast.AttrBool:
			g.appendStatic(" " + attr.Name)
		case ast.AttrString:
			g.appendStatic(" " + attr.Name + `="` + stdhtml.EscapeString(attr.Value) + `"`)
		case ast.AttrExpression:
			g.flushStatic()
			g.emitAttrWrite(attr.Name, attr.Expr, attr.Span)
		}
	}
	if elem.SelfClose {
		g.appendStatic(" />")
		return nil
	}
	g.appendStatic(">")
	if err := g.emitNodes(elem.Children, false, false); err != nil {
		return err
	}
	if !isVoid(elem.Name) {
		g.appendStatic("</" + elem.Name + ">")
	}
	return nil
}

func (g *generator) emitComponentCall(resolved *compiler.ResolvedComponent, elem *ast.Element) error {
	g.flushStatic()
	args := map[string]string{}
	for _, attr := range elem.Attributes {
		if attr.MetaSlot {
			continue
		}
		args[attr.Name] = propExpr(attr)
	}
	slots := groupSlots(elem.Children)
	callName := fmt.Sprintf("render%s", resolved.Component.Decl.Name)
	slotType := slotTypeName(resolved.Component.Decl.Name)
	if resolved.External {
		callName = fmt.Sprintf("%s.Render%sWithSlots", resolved.ImportAlias, resolved.Component.Decl.Name)
		slotType = fmt.Sprintf("%s.%s", resolved.ImportAlias, slotType)
	}
	g.line("if err := %s(w, %s{", callName, slotType)
	g.indent++
	for _, slot := range resolved.Component.Slots {
		nodes := slots[slot]
		if len(nodes) == 0 {
			continue
		}
		if forwarded, ok := forwardedSlotExpr(nodes); ok {
			g.line("%s: %s,", slotField(slot), forwarded)
			continue
		}
		g.line("%s: func(w %s.Writer) error {", slotField(slot), g.ioAlias)
		g.indent++
		if err := g.emitNodes(nodes, true, true); err != nil {
			return err
		}
		g.line("return nil")
		g.indent--
		g.line("},")
	}
	g.indent--
	params := make([]string, 0, len(resolved.Component.Params))
	for _, param := range resolved.Component.Params {
		params = append(params, args[param.Name])
	}
	g.line("}%s); err != nil {", callArgs(params))
	g.indent++
	g.line("return err")
	g.indent--
	g.line("}")
	return nil
}

func groupSlots(children []ast.Node) map[string][]ast.Node {
	out := map[string][]ast.Node{}
	for _, child := range children {
		name := "default"
		if slot, ok := childSlotName(child); ok {
			name = slot
		}
		out[name] = append(out[name], child)
	}
	return out
}

func childSlotName(node ast.Node) (string, bool) {
	elem, ok := node.(*ast.Element)
	if !ok {
		return "", false
	}
	if elem.Name == "slot" {
		if attr, ok := elem.Attr("name"); ok && attr.Kind == ast.AttrString && attr.Value != "" {
			return attr.Value, true
		}
		return "default", true
	}
	for _, attr := range elem.Attributes {
		if attr.Name == "slot" && attr.Kind == ast.AttrString {
			return attr.Value, true
		}
	}
	return "", false
}

func forwardedSlotExpr(nodes []ast.Node) (string, bool) {
	if len(nodes) != 1 {
		return "", false
	}
	return forwardedSlotExprNode(nodes[0])
}

func forwardedSlotExprNode(node ast.Node) (string, bool) {
	elem, ok := node.(*ast.Element)
	if !ok {
		return "", false
	}
	if elem.Name == "fragment" {
		for _, attr := range elem.Attributes {
			if !attr.MetaSlot {
				return "", false
			}
		}
		return forwardedSlotExpr(elem.Children)
	}
	if elem.Name != "slot" {
		return "", false
	}
	name := "default"
	if attr, ok := elem.Attr("name"); ok && attr.Kind == ast.AttrString && attr.Value != "" {
		name = attr.Value
	}
	return "__gsx_slots." + slotField(name), true
}

func propExpr(attr ast.Attribute) string {
	switch attr.Kind {
	case ast.AttrString:
		return strconv.Quote(attr.Value)
	case ast.AttrBool:
		return "true"
	default:
		return attr.Expr
	}
}

func callArgs(args []string) string {
	if len(args) == 0 {
		return ""
	}
	return ", " + strings.Join(args, ", ")
}

func ensureImport(byPath map[string]importSpec, pkgPath, preferred string) string {
	if imp, ok := byPath[pkgPath]; ok {
		if imp.Alias == "" {
			return path.Base(imp.Path)
		}
		return imp.Alias
	}
	byPath[pkgPath] = importSpec{Alias: preferred, Path: pkgPath}
	return preferred
}

func slotTypeName(component string) string {
	return "GSX" + component + "Slots"
}

func slotField(name string) string {
	if name == "default" || name == "" {
		return "Default"
	}
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '-' || r == '_' || r == ':' || r == '.'
	})
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	joined := strings.Join(parts, "")
	if joined == "" {
		return "Default"
	}
	return joined
}

func (g *generator) paramSignature(params []ast.Param) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, 0, len(params))
	for _, param := range params {
		parts = append(parts, fmt.Sprintf(", %s %s", param.Name, param.Type))
	}
	return strings.Join(parts, "")
}

func (g *generator) paramNames(params []ast.Param) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, 0, len(params))
	for _, param := range params {
		parts = append(parts, param.Name)
	}
	return strings.Join(parts, ", ")
}

func (g *generator) line(format string, args ...any) {
	if format != "" {
		g.buf.WriteString(strings.Repeat("\t", g.indent))
		g.buf.WriteString(fmt.Sprintf(format, args...))
	}
	g.buf.WriteByte('\n')
}

func (g *generator) appendStatic(s string) {
	if s == "" {
		return
	}
	g.static.WriteString(s)
}

func (g *generator) flushStatic() {
	if g.static.Len() == 0 {
		return
	}
	g.writeString(g.static.String())
	g.static.Reset()
}

func (g *generator) writeString(s string) {
	g.line("if err := %s.WriteString(w, %q); err != nil {", g.rtAlias, s)
	g.indent++
	g.line("return err")
	g.indent--
	g.line("}")
}

func (g *generator) emitExprWrite(code string, span diagnostics.Span) {
	switch g.pkg.ExprKind(span) {
	case compiler.ValueKindString, compiler.ValueKindBytes:
		g.line("if err := %s.WriteEscapedString(w, string(%s)); err != nil {", g.rtAlias, code)
	case compiler.ValueKindBool:
		g.line("if err := %s.WriteBool(w, bool(%s)); err != nil {", g.rtAlias, code)
	case compiler.ValueKindInt:
		g.line("if err := %s.WriteInt64(w, int64(%s)); err != nil {", g.rtAlias, code)
	case compiler.ValueKindUint:
		g.line("if err := %s.WriteUint64(w, uint64(%s)); err != nil {", g.rtAlias, code)
	case compiler.ValueKindFloat:
		g.line("if err := %s.WriteFloat64(w, float64(%s)); err != nil {", g.rtAlias, code)
	default:
		g.line("if err := %s.WriteEscaped(w, %s); err != nil {", g.rtAlias, code)
	}
	g.indent++
	g.line("return err")
	g.indent--
	g.line("}")
}

func (g *generator) emitAttrWrite(name, code string, span diagnostics.Span) {
	boolean := isBooleanAttribute(name)
	switch g.pkg.ExprKind(span) {
	case compiler.ValueKindString, compiler.ValueKindBytes:
		g.line("if err := %s.WriteAttrString(w, %q, string(%s)); err != nil {", g.rtAlias, name, code)
	case compiler.ValueKindBool:
		if boolean {
			g.line("if err := %s.WriteBoolAttr(w, %q, bool(%s)); err != nil {", g.rtAlias, name, code)
		} else {
			g.line("if err := %s.WriteAttrBool(w, %q, bool(%s)); err != nil {", g.rtAlias, name, code)
		}
	case compiler.ValueKindInt:
		g.line("if err := %s.WriteAttrInt64(w, %q, int64(%s)); err != nil {", g.rtAlias, name, code)
	case compiler.ValueKindUint:
		g.line("if err := %s.WriteAttrUint64(w, %q, uint64(%s)); err != nil {", g.rtAlias, name, code)
	case compiler.ValueKindFloat:
		g.line("if err := %s.WriteAttrFloat64(w, %q, float64(%s)); err != nil {", g.rtAlias, name, code)
	default:
		g.line("if err := %s.WriteAttr(w, %q, %s, %t); err != nil {", g.rtAlias, name, code, boolean)
	}
	g.indent++
	g.line("return err")
	g.indent--
	g.line("}")
}

var booleanAttrs = map[string]bool{
	"allowfullscreen": true,
	"async":           true,
	"autofocus":       true,
	"autoplay":        true,
	"checked":         true,
	"controls":        true,
	"default":         true,
	"defer":           true,
	"disabled":        true,
	"formnovalidate":  true,
	"hidden":          true,
	"ismap":           true,
	"loop":            true,
	"multiple":        true,
	"muted":           true,
	"nomodule":        true,
	"novalidate":      true,
	"open":            true,
	"playsinline":     true,
	"readonly":        true,
	"required":        true,
	"reversed":        true,
	"selected":        true,
}

func isBooleanAttribute(name string) bool {
	return booleanAttrs[strings.ToLower(name)]
}

func isVoid(name string) bool {
	switch name {
	case "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr":
		return true
	default:
		return false
	}
}
