// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXMetricCardSlots struct{}

func RenderMetricCard(w gsxio.Writer, metric Metric) error {
	return renderMetricCard(w, GSXMetricCardSlots{}, metric)
}

func RenderMetricCardWithSlots(w gsxio.Writer, slots GSXMetricCardSlots, metric Metric) error {
	return renderMetricCard(w, slots, metric)
}

func renderMetricCard(w gsxio.Writer, __gsx_slots GSXMetricCardSlots, metric Metric) error {
	if err := gsxrt.WriteString(w, "<article class=\"metric-card\"><h2>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(metric.Value)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</h2><p>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(metric.Label)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</p></article>"); err != nil {
		return err
	}
	return nil
}

type GSXDashboardLayoutSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
}

func RenderDashboardLayout(w gsxio.Writer, title string) error {
	return renderDashboardLayout(w, GSXDashboardLayoutSlots{}, title)
}

func RenderDashboardLayoutWithSlots(w gsxio.Writer, slots GSXDashboardLayoutSlots, title string) error {
	return renderDashboardLayout(w, slots, title)
}

func renderDashboardLayout(w gsxio.Writer, __gsx_slots GSXDashboardLayoutSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title>"); err != nil {
		return err
	}
	if __gsx_slots.Head != nil {
		if err := __gsx_slots.Head(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</head><body><aside class=\"sidebar\"><nav><a href=\"/\">Overview</a><a href=\"/users\">Users</a><a href=\"/jobs\">Jobs</a></nav></aside><section class=\"content\">"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</section></body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXDashboardPageSlots struct{}

func RenderDashboardPage(w gsxio.Writer, data DashboardData) error {
	return renderDashboardPage(w, GSXDashboardPageSlots{}, data)
}

func RenderDashboardPageWithSlots(w gsxio.Writer, slots GSXDashboardPageSlots, data DashboardData) error {
	return renderDashboardPage(w, slots, data)
}

func renderDashboardPage(w gsxio.Writer, __gsx_slots GSXDashboardPageSlots, data DashboardData) error {
	{
		title := data.Title
		if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
			return err
		}
		if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
			return err
		}
		if err := gsxrt.WriteString(w, "</title><meta name=\"description\" content=\"Example admin dashboard rendered with GSX\" /></head><body><aside class=\"sidebar\"><nav><a href=\"/\">Overview</a><a href=\"/users\">Users</a><a href=\"/jobs\">Jobs</a></nav></aside><section class=\"content\"><header><h1>"); err != nil {
			return err
		}
		if err := gsxrt.WriteEscapedString(w, string(data.Title)); err != nil {
			return err
		}
		if err := gsxrt.WriteString(w, "</h1><form method=\"post\" action=\"/filters\"><label for=\"range\">Time range</label><select id=\"range\" name=\"range\"><option value=\"24h\">Last 24 hours</option><option value=\"7d\">Last 7 days</option><option value=\"30d\">Last 30 days</option></select><button type=\"submit\">Apply</button></form></header><section class=\"metrics-grid\">"); err != nil {
			return err
		}
		for _, metric := range data.Metrics {
			{
				metric := metric
				if err := gsxrt.WriteString(w, "<article class=\"metric-card\"><h2>"); err != nil {
					return err
				}
				if err := gsxrt.WriteEscapedString(w, string(metric.Value)); err != nil {
					return err
				}
				if err := gsxrt.WriteString(w, "</h2><p>"); err != nil {
					return err
				}
				if err := gsxrt.WriteEscapedString(w, string(metric.Label)); err != nil {
					return err
				}
				if err := gsxrt.WriteString(w, "</p></article>"); err != nil {
					return err
				}
			}
		}
		if err := gsxrt.WriteString(w, "</section></section></body></html>"); err != nil {
			return err
		}
	}
	return nil
}
