// Code generated by gsx. DO NOT EDIT.

package layouts

import (
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXShellSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
}

func RenderShell(w gsxio.Writer, title string) error {
	return renderShell(w, GSXShellSlots{}, title)
}

func RenderShellWithSlots(w gsxio.Writer, slots GSXShellSlots, title string) error {
	return renderShell(w, slots, title)
}

func renderShell(w gsxio.Writer, __gsx_slots GSXShellSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title>"); err != nil {
		return err
	}
	if __gsx_slots.Head != nil {
		if err := __gsx_slots.Head(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</head><body><header class=\"site-header\"><strong>Shared Layouts</strong></header><main>"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</main></body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXPanelSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
}

func RenderPanel(w gsxio.Writer, title string) error {
	return renderPanel(w, GSXPanelSlots{}, title)
}

func RenderPanelWithSlots(w gsxio.Writer, slots GSXPanelSlots, title string) error {
	return renderPanel(w, slots, title)
}

func renderPanel(w gsxio.Writer, __gsx_slots GSXPanelSlots, title string) error {
	if err := renderShell(w, GSXShellSlots{
		Head: __gsx_slots.Head,
		Default: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<section class=\"panel-shell\">"); err != nil {
				return err
			}
			if __gsx_slots.Default != nil {
				if err := __gsx_slots.Default(w); err != nil {
					return err
				}
			}
			if err := gsxrt.WriteString(w, "</section>"); err != nil {
				return err
			}
			return nil
		},
	}, title); err != nil {
		return err
	}
	return nil
}
