// Code generated by gsx. DO NOT EDIT.

package layouts

import (
	gsxbytes "bytes"
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXShellSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
}

func RenderShell(w gsxio.Writer, title string) error {
	return renderShell(w, GSXShellSlots{}, title)
}

func RenderShellBuffer(__gsx_buf *gsxbytes.Buffer, title string) error {
	__gsx_buf.Grow(276)
	return renderShell(__gsx_buf, GSXShellSlots{}, title)
}

func RenderShellWithSlots(w gsxio.Writer, slots GSXShellSlots, title string) error {
	return renderShell(w, slots, title)
}

func RenderShellBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXShellSlots, title string) error {
	__gsx_buf.Grow(276)
	return renderShell(__gsx_buf, slots, title)
}

func renderShell(w gsxio.Writer, __gsx_slots GSXShellSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title>"); err != nil {
		return err
	}
	if __gsx_slots.Head != nil {
		if err := __gsx_slots.Head(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</head><body><header class=\"site-header\"><strong>Shared Layouts</strong></header><main>"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</main></body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXPanelSlots struct {
	Head    func(gsxio.Writer) error
	Default func(gsxio.Writer) error
}

func RenderPanel(w gsxio.Writer, title string) error {
	return renderPanel(w, GSXPanelSlots{}, title)
}

func RenderPanelBuffer(__gsx_buf *gsxbytes.Buffer, title string) error {
	__gsx_buf.Grow(315)
	return renderPanel(__gsx_buf, GSXPanelSlots{}, title)
}

func RenderPanelWithSlots(w gsxio.Writer, slots GSXPanelSlots, title string) error {
	return renderPanel(w, slots, title)
}

func RenderPanelBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXPanelSlots, title string) error {
	__gsx_buf.Grow(315)
	return renderPanel(__gsx_buf, slots, title)
}

func renderPanel(w gsxio.Writer, __gsx_slots GSXPanelSlots, title string) error {
	{
		if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>"); err != nil {
			return err
		}
		if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
			return err
		}
		if err := gsxrt.WriteString(w, "</title>"); err != nil {
			return err
		}
		if __gsx_slots.Head != nil {
			if err := __gsx_slots.Head(w); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</head><body><header class=\"site-header\"><strong>Shared Layouts</strong></header><main><section class=\"panel-shell\">"); err != nil {
			return err
		}
		if __gsx_slots.Default != nil {
			if err := __gsx_slots.Default(w); err != nil {
				return err
			}
		}
		if err := gsxrt.WriteString(w, "</section></main></body></html>"); err != nil {
			return err
		}
	}
	return nil
}
