// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxbytes "bytes"
	shared "github.com/jlcsoftgenie/gsx/examples/shared/layouts"
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXHomePageSlots struct{}

func RenderHomePage(w gsxio.Writer, title string, description string) error {
	return renderHomePage(w, GSXHomePageSlots{}, title, description)
}

func RenderHomePageBuffer(__gsx_buf *gsxbytes.Buffer, title string, description string) error {
	__gsx_buf.Grow(0)
	return renderHomePage(__gsx_buf, GSXHomePageSlots{}, title, description)
}

func RenderHomePageWithSlots(w gsxio.Writer, slots GSXHomePageSlots, title string, description string) error {
	return renderHomePage(w, slots, title, description)
}

func RenderHomePageBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXHomePageSlots, title string, description string) error {
	__gsx_buf.Grow(0)
	return renderHomePage(__gsx_buf, slots, title, description)
}

func renderHomePage(w gsxio.Writer, __gsx_slots GSXHomePageSlots, title string, description string) error {
	if err := shared.RenderPanelWithSlots(w, shared.GSXPanelSlots{
		Head: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<meta name=\"description\""); err != nil {
				return err
			}
			if err := gsxrt.WriteAttrString(w, "content", string(description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, " />"); err != nil {
				return err
			}
			return nil
		},
		Default: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<article><h1>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</h1><p>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</p></article>"); err != nil {
				return err
			}
			return nil
		},
	}, title); err != nil {
		return err
	}
	return nil
}
