// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxbytes "bytes"
	shared "github.com/jlcsoftgenie/gsx/examples/shared/layouts"
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXSiteNavSlots struct{}

func RenderSiteNav(w gsxio.Writer) error {
	return renderSiteNav(w, GSXSiteNavSlots{})
}

func RenderSiteNavBuffer(__gsx_buf *gsxbytes.Buffer) error {
	__gsx_buf.Grow(118)
	return renderSiteNav(__gsx_buf, GSXSiteNavSlots{})
}

func RenderSiteNavWithSlots(w gsxio.Writer, slots GSXSiteNavSlots) error {
	return renderSiteNav(w, slots)
}

func RenderSiteNavBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXSiteNavSlots) error {
	__gsx_buf.Grow(118)
	return renderSiteNav(__gsx_buf, slots)
}

func renderSiteNav(w gsxio.Writer, __gsx_slots GSXSiteNavSlots) error {
	if err := gsxrt.WriteString(w, "<nav><a href=\"/\">Home</a><span> | </span><a href=\"/users\">Users</a><span> | </span><a href=\"/healthz\">Health</a></nav>"); err != nil {
		return err
	}
	return nil
}

type GSXUserRowSlots struct{}

func RenderUserRow(w gsxio.Writer, user User) error {
	return renderUserRow(w, GSXUserRowSlots{}, user)
}

func RenderUserRowBuffer(__gsx_buf *gsxbytes.Buffer, user User) error {
	__gsx_buf.Grow(132)
	return renderUserRow(__gsx_buf, GSXUserRowSlots{}, user)
}

func RenderUserRowWithSlots(w gsxio.Writer, slots GSXUserRowSlots, user User) error {
	return renderUserRow(w, slots, user)
}

func RenderUserRowBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXUserRowSlots, user User) error {
	__gsx_buf.Grow(132)
	return renderUserRow(__gsx_buf, slots, user)
}

func renderUserRow(w gsxio.Writer, __gsx_slots GSXUserRowSlots, user User) error {
	if err := gsxrt.WriteString(w, "<tr><td>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Role)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
		return err
	}
	return nil
}

type GSXUserTableSlots struct{}

func RenderUserTable(w gsxio.Writer, users []User) error {
	return renderUserTable(w, GSXUserTableSlots{}, users)
}

func RenderUserTableBuffer(__gsx_buf *gsxbytes.Buffer, users []User) error {
	__gsx_buf.Grow(226 + len(users)*132)
	return renderUserTable(__gsx_buf, GSXUserTableSlots{}, users)
}

func RenderUserTableWithSlots(w gsxio.Writer, slots GSXUserTableSlots, users []User) error {
	return renderUserTable(w, slots, users)
}

func RenderUserTableBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXUserTableSlots, users []User) error {
	__gsx_buf.Grow(226 + len(users)*132)
	return renderUserTable(__gsx_buf, slots, users)
}

func renderUserTable(w gsxio.Writer, __gsx_slots GSXUserTableSlots, users []User) error {
	if err := gsxrt.WriteString(w, "<table><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>"); err != nil {
		return err
	}
	for _, user := range users {
		{
			if err := gsxrt.WriteString(w, "<tr><td>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(user.Role)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
				return err
			}
		}
	}
	if err := gsxrt.WriteString(w, "</tbody></table>"); err != nil {
		return err
	}
	return nil
}

type GSXHomePageSlots struct{}

func RenderHomePage(w gsxio.Writer, title string, description string, users []User) error {
	return renderHomePage(w, GSXHomePageSlots{}, title, description, users)
}

func RenderHomePageBuffer(__gsx_buf *gsxbytes.Buffer, title string, description string, users []User) error {
	__gsx_buf.Grow(0)
	return renderHomePage(__gsx_buf, GSXHomePageSlots{}, title, description, users)
}

func RenderHomePageWithSlots(w gsxio.Writer, slots GSXHomePageSlots, title string, description string, users []User) error {
	return renderHomePage(w, slots, title, description, users)
}

func RenderHomePageBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXHomePageSlots, title string, description string, users []User) error {
	__gsx_buf.Grow(0)
	return renderHomePage(__gsx_buf, slots, title, description, users)
}

func renderHomePage(w gsxio.Writer, __gsx_slots GSXHomePageSlots, title string, description string, users []User) error {
	if err := shared.RenderPanelWithSlots(w, shared.GSXPanelSlots{
		Head: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<meta name=\"description\""); err != nil {
				return err
			}
			if err := gsxrt.WriteAttrString(w, "content", string(description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, " />"); err != nil {
				return err
			}
			return nil
		},
		Default: func(w gsxio.Writer) error {
			{
				if err := gsxrt.WriteString(w, "<nav><a href=\"/\">Home</a><span> | </span><a href=\"/users\">Users</a><span> | </span><a href=\"/healthz\">Health</a></nav>"); err != nil {
					return err
				}
			}
			if err := gsxrt.WriteString(w, "<section><h1>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</h1><p>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(description)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</p><p>Total users: "); err != nil {
				return err
			}
			if err := gsxrt.WriteInt64(w, int64(len(users))); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</p><p><a href=\"/users\">Browse the user directory</a></p></section>"); err != nil {
				return err
			}
			return nil
		},
	}, title); err != nil {
		return err
	}
	return nil
}

type GSXUsersPageSlots struct{}

func RenderUsersPage(w gsxio.Writer, title string, users []User) error {
	return renderUsersPage(w, GSXUsersPageSlots{}, title, users)
}

func RenderUsersPageBuffer(__gsx_buf *gsxbytes.Buffer, title string, users []User) error {
	__gsx_buf.Grow(0)
	return renderUsersPage(__gsx_buf, GSXUsersPageSlots{}, title, users)
}

func RenderUsersPageWithSlots(w gsxio.Writer, slots GSXUsersPageSlots, title string, users []User) error {
	return renderUsersPage(w, slots, title, users)
}

func RenderUsersPageBufferWithSlots(__gsx_buf *gsxbytes.Buffer, slots GSXUsersPageSlots, title string, users []User) error {
	__gsx_buf.Grow(0)
	return renderUsersPage(__gsx_buf, slots, title, users)
}

func renderUsersPage(w gsxio.Writer, __gsx_slots GSXUsersPageSlots, title string, users []User) error {
	if err := shared.RenderPanelWithSlots(w, shared.GSXPanelSlots{
		Head: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<meta name=\"description\" content=\"Example users page rendered in a standard webserver.\" />"); err != nil {
				return err
			}
			return nil
		},
		Default: func(w gsxio.Writer) error {
			{
				if err := gsxrt.WriteString(w, "<nav><a href=\"/\">Home</a><span> | </span><a href=\"/users\">Users</a><span> | </span><a href=\"/healthz\">Health</a></nav>"); err != nil {
					return err
				}
			}
			if err := gsxrt.WriteString(w, "<section><h1>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</h1>"); err != nil {
				return err
			}
			if len(users) == 0 {
				if err := gsxrt.WriteString(w, "<p>No users available.</p>"); err != nil {
					return err
				}
			} else {
				{
					if err := gsxrt.WriteString(w, "<table><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>"); err != nil {
						return err
					}
					for _, user := range users {
						{
							if err := gsxrt.WriteString(w, "<tr><td>"); err != nil {
								return err
							}
							if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
								return err
							}
							if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
								return err
							}
							if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
								return err
							}
							if err := gsxrt.WriteString(w, "</td><td>"); err != nil {
								return err
							}
							if err := gsxrt.WriteEscapedString(w, string(user.Role)); err != nil {
								return err
							}
							if err := gsxrt.WriteString(w, "</td></tr>"); err != nil {
								return err
							}
						}
					}
					if err := gsxrt.WriteString(w, "</tbody></table>"); err != nil {
						return err
					}
				}
			}
			if err := gsxrt.WriteString(w, "</section>"); err != nil {
				return err
			}
			return nil
		},
	}, title); err != nil {
		return err
	}
	return nil
}
