// Code generated by gsx. DO NOT EDIT.

package main

import (
	gsxrt "github.com/jlcsoftgenie/gsx/runtime"
	gsxio "io"
)

type GSXAppLayoutSlots struct {
	Default func(gsxio.Writer) error
}

func RenderAppLayout(w gsxio.Writer, title string) error {
	return renderAppLayout(w, GSXAppLayoutSlots{}, title)
}

func RenderAppLayoutWithSlots(w gsxio.Writer, slots GSXAppLayoutSlots, title string) error {
	return renderAppLayout(w, slots, title)
}

func renderAppLayout(w gsxio.Writer, __gsx_slots GSXAppLayoutSlots, title string) error {
	if err := gsxrt.WriteString(w, "<!doctype html><html><head><meta charset=\"utf-8\" /><title>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /></head><body>"); err != nil {
		return err
	}
	if __gsx_slots.Default != nil {
		if err := __gsx_slots.Default(w); err != nil {
			return err
		}
	}
	if err := gsxrt.WriteString(w, "</body></html>"); err != nil {
		return err
	}
	return nil
}

type GSXUserCardSlots struct{}

func RenderUserCard(w gsxio.Writer, user User) error {
	return renderUserCard(w, GSXUserCardSlots{}, user)
}

func RenderUserCardWithSlots(w gsxio.Writer, slots GSXUserCardSlots, user User) error {
	return renderUserCard(w, slots, user)
}

func renderUserCard(w gsxio.Writer, __gsx_slots GSXUserCardSlots, user User) error {
	if err := gsxrt.WriteString(w, "<li class=\"user-card\"><img"); err != nil {
		return err
	}
	if err := gsxrt.WriteAttrString(w, "src", string(user.AvatarURL)); err != nil {
		return err
	}
	if err := gsxrt.WriteAttrString(w, "alt", string(user.Name)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, " />"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "<div class=\"content\"><h3>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Name)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</h3><p>"); err != nil {
		return err
	}
	if err := gsxrt.WriteEscapedString(w, string(user.Email)); err != nil {
		return err
	}
	if err := gsxrt.WriteString(w, "</p></div></li>"); err != nil {
		return err
	}
	return nil
}

type GSXUsersPageSlots struct{}

func RenderUsersPage(w gsxio.Writer, title string, users []User) error {
	return renderUsersPage(w, GSXUsersPageSlots{}, title, users)
}

func RenderUsersPageWithSlots(w gsxio.Writer, slots GSXUsersPageSlots, title string, users []User) error {
	return renderUsersPage(w, slots, title, users)
}

func renderUsersPage(w gsxio.Writer, __gsx_slots GSXUsersPageSlots, title string, users []User) error {
	if err := renderAppLayout(w, GSXAppLayoutSlots{
		Default: func(w gsxio.Writer) error {
			if err := gsxrt.WriteString(w, "<main class=\"container\"><h1>"); err != nil {
				return err
			}
			if err := gsxrt.WriteEscapedString(w, string(title)); err != nil {
				return err
			}
			if err := gsxrt.WriteString(w, "</h1>"); err != nil {
				return err
			}
			if len(users) == 0 {
				if err := gsxrt.WriteString(w, "<p>No users found.</p>"); err != nil {
					return err
				}
			} else {
				if err := gsxrt.WriteString(w, "<ul class=\"users\">"); err != nil {
					return err
				}
				for _, user := range users {
					if err := renderUserCard(w, GSXUserCardSlots{}, user); err != nil {
						return err
					}
				}
				if err := gsxrt.WriteString(w, "</ul>"); err != nil {
					return err
				}
			}
			if err := gsxrt.WriteString(w, "</main>"); err != nil {
				return err
			}
			return nil
		},
	}, title); err != nil {
		return err
	}
	return nil
}
